[11-01 13:49:13.000][ info][f:/y3_maps/war3/maps/EntryMap/script/y3/init.lua:155]: LuaLib版本：	241028
[11-01 13:49:13.000][debug][f:/y3_maps/war3/maps/EntryMap/script/y3\util\network.lua:34]: Network 初始化：	{Network|127.0.0.1|12345|new}
[11-01 13:49:13.000][debug][f:/y3_maps/war3/maps/EntryMap/script/y3\util\network.lua:130]: Network 已连接：	{Network|127.0.0.1|12345|started}
[11-01 13:49:13.033][debug][f:/y3_maps/war3/maps/EntryMap/script/y3\util\log.lua:136]: Hello, Y3!
[11-01 13:49:13.033][error][?]: ea_prefab_not_exist
error during Python call: ea_prefab_not_exist
stack traceback:
	[C]: in field 'create_unit'
	.../maps/EntryMap/script/y3\object\editable_object\unit.lua:344: in function 'y3.object.editable_object.unit.create_unit'
	f:/y3_maps/war3/maps/EntryMap/script/scripts\mgr\MapMgr.lua:25: in function 'scripts.mgr.MapMgr.create_building'
	f:/y3_maps/war3/maps/EntryMap/script/scripts\mgr\MapMgr.lua:8: in function 'scripts.mgr.MapMgr.initMap'
	.../war3/maps/EntryMap/script/scripts\mgr\PlayerMgr.lua:81: in function 'scripts.mgr.PlayerMgr.initPlayers'
	.../war3/maps/EntryMap/script/scripts\mgr\GameMgr.lua:9: in function 'scripts.mgr.GameMgr.gameInit'
	f:/y3_maps/war3/maps/EntryMap/script/main.lua:14: in function <f:/y3_maps/war3/maps/EntryMap/script/main.lua:12>
	[C]: in function 'xpcall'
	f:/y3_maps/war3/maps/EntryMap/script/y3\util\trigger.lua:168: in function 'y3.util.trigger.execute'
	f:/y3_maps/war3/maps/EntryMap/script/y3\util\event.lua:185: in method 'dispatch'
	.../war3/maps/EntryMap/script/y3\util\event_manager.lua:168: in method 'dispatch'
	f:/y3_maps/war3/maps/EntryMap/script/y3\game\game_event.lua:57: in function 'y3.game.game_event.event_notify'
	.../maps/EntryMap/script/y3\game\py_event_subscribe.lua:280: in function <.../maps/EntryMap/script/y3\game\py_event_subscribe.lua:278>
